apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    version: v1
spec:
  containers:
    - name: mysql57
      image: mysql:5.7
      ports:
      - containerPort: 3306
        name: db-port
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
        - name: MYSQL_USER
          value: app
        - name: MYSQL_PASSWORD
          value: "12345678"
        - name: MYSQL_DATABASE
          value: geoserviciosbd

    - name: api-feedback
      image: gcr.io/mitocode-304321/api-feedback:latest
      ports:
      - containerPort: 8080
        protocol: TCP
      env:
        - name: host
          value: "localhost"
        - name: port
          value: "3306"
        - name: database
          value: "geoserviciosbd"
        - name: password
          value: "12345678"
        - name: username
          value: app
