apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-seguridad
  labels:
    app: api-seguridad
    version: v1
  namespace: name2
spec:
  selector: #permite seleccionar un conjunto de objetos que cumplan las condiciones
    matchLabels:
      app: api-seguridad
      version: v1
  replicas: 1 #replicaset
  strategy:
    type: RollingUpdate # otro valor ->  Recreate (evita que el controlador actualice de forma automática)
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template: # Plantilla que define los containers
    metadata:
      labels:
        app: api-seguridad
        version: v1
    spec:
      containers:
        - name: api-seguridad 
          image: gcr.io/mitocode-304321/api-seguridad
          ports:
              - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "1"