apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    version: v1
  namespace: name2
spec:
  containers:
   - name: ubuntu
     image: ubuntu:18.04
     command: ["sleep", "3600"]
