apiVersion: v1
kind: Service
metadata:
  name: api-seguridad-ndp
  namespace: name2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-seguridad
  type: NodePort #Ingress nativo necesita un svc tipo NodePort